// Code generated by protoc-gen-go-drpc. DO NOT EDIT.
// protoc-gen-go-drpc version: v0.0.33
// source: inteld/proto/inteld.proto

package proto

import (
	context "context"
	errors "errors"
	protojson "google.golang.org/protobuf/encoding/protojson"
	proto "google.golang.org/protobuf/proto"
	drpc "storj.io/drpc"
	drpcerr "storj.io/drpc/drpcerr"
)

type drpcEncoding_File_inteld_proto_inteld_proto struct{}

func (drpcEncoding_File_inteld_proto_inteld_proto) Marshal(msg drpc.Message) ([]byte, error) {
	return proto.Marshal(msg.(proto.Message))
}

func (drpcEncoding_File_inteld_proto_inteld_proto) MarshalAppend(buf []byte, msg drpc.Message) ([]byte, error) {
	return proto.MarshalOptions{}.MarshalAppend(buf, msg.(proto.Message))
}

func (drpcEncoding_File_inteld_proto_inteld_proto) Unmarshal(buf []byte, msg drpc.Message) error {
	return proto.Unmarshal(buf, msg.(proto.Message))
}

func (drpcEncoding_File_inteld_proto_inteld_proto) JSONMarshal(msg drpc.Message) ([]byte, error) {
	return protojson.Marshal(msg.(proto.Message))
}

func (drpcEncoding_File_inteld_proto_inteld_proto) JSONUnmarshal(buf []byte, msg drpc.Message) error {
	return protojson.Unmarshal(buf, msg.(proto.Message))
}

type DRPCIntelDaemonClient interface {
	DRPCConn() drpc.Conn

	Register(ctx context.Context, in *RegisterRequest) (DRPCIntelDaemon_RegisterClient, error)
	RecordInvocation(ctx context.Context, in *ReportInvocationRequest) (*Empty, error)
	ReportPath(ctx context.Context, in *ReportPathRequest) (*Empty, error)
}

type drpcIntelDaemonClient struct {
	cc drpc.Conn
}

func NewDRPCIntelDaemonClient(cc drpc.Conn) DRPCIntelDaemonClient {
	return &drpcIntelDaemonClient{cc}
}

func (c *drpcIntelDaemonClient) DRPCConn() drpc.Conn { return c.cc }

func (c *drpcIntelDaemonClient) Register(ctx context.Context, in *RegisterRequest) (DRPCIntelDaemon_RegisterClient, error) {
	stream, err := c.cc.NewStream(ctx, "/inteld.IntelDaemon/Register", drpcEncoding_File_inteld_proto_inteld_proto{})
	if err != nil {
		return nil, err
	}
	x := &drpcIntelDaemon_RegisterClient{stream}
	if err := x.MsgSend(in, drpcEncoding_File_inteld_proto_inteld_proto{}); err != nil {
		return nil, err
	}
	if err := x.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DRPCIntelDaemon_RegisterClient interface {
	drpc.Stream
	Recv() (*SystemResponse, error)
}

type drpcIntelDaemon_RegisterClient struct {
	drpc.Stream
}

func (x *drpcIntelDaemon_RegisterClient) GetStream() drpc.Stream {
	return x.Stream
}

func (x *drpcIntelDaemon_RegisterClient) Recv() (*SystemResponse, error) {
	m := new(SystemResponse)
	if err := x.MsgRecv(m, drpcEncoding_File_inteld_proto_inteld_proto{}); err != nil {
		return nil, err
	}
	return m, nil
}

func (x *drpcIntelDaemon_RegisterClient) RecvMsg(m *SystemResponse) error {
	return x.MsgRecv(m, drpcEncoding_File_inteld_proto_inteld_proto{})
}

func (c *drpcIntelDaemonClient) RecordInvocation(ctx context.Context, in *ReportInvocationRequest) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/inteld.IntelDaemon/RecordInvocation", drpcEncoding_File_inteld_proto_inteld_proto{}, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drpcIntelDaemonClient) ReportPath(ctx context.Context, in *ReportPathRequest) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/inteld.IntelDaemon/ReportPath", drpcEncoding_File_inteld_proto_inteld_proto{}, in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

type DRPCIntelDaemonServer interface {
	Register(*RegisterRequest, DRPCIntelDaemon_RegisterStream) error
	RecordInvocation(context.Context, *ReportInvocationRequest) (*Empty, error)
	ReportPath(context.Context, *ReportPathRequest) (*Empty, error)
}

type DRPCIntelDaemonUnimplementedServer struct{}

func (s *DRPCIntelDaemonUnimplementedServer) Register(*RegisterRequest, DRPCIntelDaemon_RegisterStream) error {
	return drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

func (s *DRPCIntelDaemonUnimplementedServer) RecordInvocation(context.Context, *ReportInvocationRequest) (*Empty, error) {
	return nil, drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

func (s *DRPCIntelDaemonUnimplementedServer) ReportPath(context.Context, *ReportPathRequest) (*Empty, error) {
	return nil, drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

type DRPCIntelDaemonDescription struct{}

func (DRPCIntelDaemonDescription) NumMethods() int { return 3 }

func (DRPCIntelDaemonDescription) Method(n int) (string, drpc.Encoding, drpc.Receiver, interface{}, bool) {
	switch n {
	case 0:
		return "/inteld.IntelDaemon/Register", drpcEncoding_File_inteld_proto_inteld_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return nil, srv.(DRPCIntelDaemonServer).
					Register(
						in1.(*RegisterRequest),
						&drpcIntelDaemon_RegisterStream{in2.(drpc.Stream)},
					)
			}, DRPCIntelDaemonServer.Register, true
	case 1:
		return "/inteld.IntelDaemon/RecordInvocation", drpcEncoding_File_inteld_proto_inteld_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return srv.(DRPCIntelDaemonServer).
					RecordInvocation(
						ctx,
						in1.(*ReportInvocationRequest),
					)
			}, DRPCIntelDaemonServer.RecordInvocation, true
	case 2:
		return "/inteld.IntelDaemon/ReportPath", drpcEncoding_File_inteld_proto_inteld_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return srv.(DRPCIntelDaemonServer).
					ReportPath(
						ctx,
						in1.(*ReportPathRequest),
					)
			}, DRPCIntelDaemonServer.ReportPath, true
	default:
		return "", nil, nil, nil, false
	}
}

func DRPCRegisterIntelDaemon(mux drpc.Mux, impl DRPCIntelDaemonServer) error {
	return mux.Register(impl, DRPCIntelDaemonDescription{})
}

type DRPCIntelDaemon_RegisterStream interface {
	drpc.Stream
	Send(*SystemResponse) error
}

type drpcIntelDaemon_RegisterStream struct {
	drpc.Stream
}

func (x *drpcIntelDaemon_RegisterStream) Send(m *SystemResponse) error {
	return x.MsgSend(m, drpcEncoding_File_inteld_proto_inteld_proto{})
}

type DRPCIntelDaemon_RecordInvocationStream interface {
	drpc.Stream
	SendAndClose(*Empty) error
}

type drpcIntelDaemon_RecordInvocationStream struct {
	drpc.Stream
}

func (x *drpcIntelDaemon_RecordInvocationStream) SendAndClose(m *Empty) error {
	if err := x.MsgSend(m, drpcEncoding_File_inteld_proto_inteld_proto{}); err != nil {
		return err
	}
	return x.CloseSend()
}

type DRPCIntelDaemon_ReportPathStream interface {
	drpc.Stream
	SendAndClose(*Empty) error
}

type drpcIntelDaemon_ReportPathStream struct {
	drpc.Stream
}

func (x *drpcIntelDaemon_ReportPathStream) SendAndClose(m *Empty) error {
	if err := x.MsgSend(m, drpcEncoding_File_inteld_proto_inteld_proto{}); err != nil {
		return err
	}
	return x.CloseSend()
}
